### PR TITLE
remove the engines.yarn path from the package json

### LINKED ISSUE #7: engines.yarn must return valid semver syntax
Hi! We were using your package to help move us off of yarn and onto NPM. Our node app failed to deploy because the [`engines.yarn` line is invalid](https://github.com/mixmaxhq/deyarn/blob/master/src/index.js#L54). You can only provide a valid SEMVER string here, otherwise this will break deploys.

The solution here is to remove that path, rather than modify it. Oddly enough, `edit-json-file` doesn't have an option for `unset`-ing a line, so [I added it](https://github.com/IonicaBizau/edit-json-file/pull/12). You can pull from [my fork](https://github.com/acconrad/edit-json-file) to add this functionality in now if you'd like. I'm also going to create a pull request momentarily that will include the proposed fix.

### PR DESCRIPTION
**Pull request by acconrad**
A copy of [this PR](https://github.com/mixmaxhq/deyarn/pull/8) but simplified based on what the creator of `edit-json-file` wants to do

Fixes #7

### CODE REVIEW

**Comment by acconrad** [comment]
@spencer-brown @wearhere @lukebarton any chance this is going to get merged?

**Comment by wearhere** [comment]
thanks for the bump, left some questions on #7

**Comment by acconrad** [comment]
yup all set @wearhere !

**Comment by acconrad** [comment]
@wearhere can we get this merged? been a while

**Comment by wearhere** [comment]
@acconrad very sorry for the delay! Left some [more comments](https://github.com/mixmaxhq/deyarn/issues/7#issuecomment-450699832) on the PR and I will do a better job of monitoring my GitHub notifications :)

**Comment by wearhere** [comment]
Closing per https://github.com/mixmaxhq/deyarn/issues/7#issuecomment-450971444

**Pull request closed without merging**
